import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

// Initialize the Google GenAI SDK with the API key from environment variables
const apiKey = process.env.GEMINI_API_KEY;
const ai = apiKey ? new GoogleGenAI({ apiKey }) : null;

/**
 * Sends the structured prompt to the Gemini API and parses the response.
 * 
 * @param {string} prompt - The prompt generated by promptBuilder
 * @returns {Promise<{query: string, explanation: string, error?: string}>} The query and explanation from Gemini
 */
export const generateQuery = async (prompt) => {
  if (!ai) {
    return {
      query: "",
      explanation: "",
      error: "GEMINI_API_KEY is not configured in the backend environment variables (.env file)."
    };
  }

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json"
      }
    });

    let text = response.text;
    if (!text) {
      throw new Error("Received empty response from Gemini API.");
    }

    // Strip markdown code block wrappers if present
    text = text.trim();
    if (text.startsWith("```")) {
      text = text.replace(/^```[a-zA-Z0-9]*\s*/, "");
      text = text.replace(/\s*```$/, "");
      text = text.trim();
    }

    // Parse the strict JSON response
    const parsed = JSON.parse(text);

    return {
      sql: parsed.sql || parsed.query || "",
      query: parsed.sql || parsed.query || "",
      explanation: parsed.explanation || "",
      preview: parsed.preview || null,
    };
  } catch (error) {
    console.error("Gemini API call failed:", error);
    return {
      query: "",
      explanation: "",
      error: error.message || "Failed to generate query from Gemini API."
    };
  }
};
